# This is a basic workflow to help you get started with Actions

name: "All MSTests"

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Restore NuGet packages
        run: nuget restore "AspNetMvcEg/AspNetMvcEg.sln"
        
      - name: Build the Solution
        run: msbuild "AspNetMvcEg/AspNetMvcEg.sln"
        
      - name: Run VSTests
        run:  '& "$(vswhere -property installationPath)\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" "D:\a\AspNetMvcEg\AspNetMvcEg\AspNetMvcEg\AspNetMvcEgTest\bin\Debug\AspNetMvcEgTest.dll"'
      # Runs a set of commands using the runners shell
